---
name: Archive local maven repo

#see https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
on: workflow_dispatch

jobs:
  save-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      ## Configure JDK
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      ## Configure maven settings
      - name: Prepare maven settings
        env:
          REPOSITORY_URL: ${{ secrets.LEVIGO_NEXUS_REPO_ALL }}
          REPOSITORY_USERID: ${{ secrets.LEVIGO_NEXUS_USERNAME }}
          REPOSITORY_CREDENTIALS: ${{ secrets.LEVIGO_NEXUS_PASSWORD }}
          REPOSITORY_RELEASE_USERID: ${{ secrets.NEXUS2_USERNAME }}
          REPOSITORY_RELEASE_CREDENTIALS: ${{ secrets.NEXUS2_PASSWORD }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: |
          mkdir -p ~/.m2
          envsubst < ./.github/settings.xml > ~/.m2/settings.xml

      ## Save local maven repo
      - name: Get maven dependencies
        run: |
          mvn -B verify -DskipTests

      - name: Archive maven dependencies
        run: |
          cd ~
          tar -czf local-maven-repo.tar.gz .m2/repository/
          ls -lahn

      - name: Upload archived local maven repo
        uses: actions/upload-artifact@v2
        with:
          name: local-maven-repo
          path: ~/local-maven-repo.tar.gz
...