name: Continuous Delivery

on:
  push:
    branches: [ master ]
    paths-ignore:
      #   !! Attention!! removing the following line may produce an endless loop on the build system!!
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      STANDARD_14_FONTS_TAG_PREFIX: 'documentplatform-standard14-fonts-'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_PTA }}

      - name: Bump version and create tag
        id: semanticversion
        uses: hennejg/github-tag-action@v4.2.4
        with:
          release_branches: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ env.STANDARD_14_FONTS_TAG_PREFIX }}

      - name: Verify and print new build number
        run: |
          if echo '${{ steps.semanticversion.outputs.new_tag }}' |grep -Eq '^${{ env.STANDARD_14_FONTS_TAG_PREFIX }}[0-9]+[.][0-9]+[.][0-9]+$'; then
            echo Tag '${{ steps.semanticversion.outputs.new_tag }}', New version '${{ steps.semanticversion.outputs.new_version }}', Changelog '${{ steps.semanticversion.outputs.changelog }}'
          else
            echo 'unexpected tag format - aborting'
            exit -1
          fi

      ## Configure JDK
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      ## Enable Caching
      # Reduce cache size by excluding artifacts with the project.groupId
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            --exclude='*/repository/org/jadice/documentplatform/*'
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      ## Configure maven settings
      - name: Prepare maven settings
        env:
          REPOSITORY_URL: ${{ secrets.LEVIGO_NEXUS_REPO_ALL }}
          REPOSITORY_USERID: ${{ secrets.LEVIGO_NEXUS_USERNAME }}
          REPOSITORY_CREDENTIALS: ${{ secrets.LEVIGO_NEXUS_PASSWORD }}
          REPOSITORY_RELEASE_USERID: ${{ secrets.NEXUS2_USERNAME }}
          REPOSITORY_RELEASE_CREDENTIALS: ${{ secrets.NEXUS2_PASSWORD }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: |
          mkdir -p ~/.m2
          envsubst < ./.github/settings.xml > ~/.m2/settings.xml

      ## Build with maven
      - name: Set version
        id: version
        run: |
          echo Releasing as ${{ steps.semanticversion.outputs.new_version }}
          mvn versions:set -DnewVersion=${{ steps.semanticversion.outputs.new_version }}

      - name: Perform build
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -B verify -Dmaven.test.failure.ignore=true

      ## Publish test report
      - name: Publish Test Report for JDK 8
        id: test-report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_test_failures: true
          check_name: Test Report for JDK 8

      ## Deploy
      - name: Deploy packages
        run: mvn -B deploy -DskipTests -Dmaven.install.skip=true

      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -Dmaven.test.skip.exec=true -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/levigo/documentplatform-standard14-fonts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ## checkout a second repository - we need this one to be able to notify JIRA
      - uses: actions/checkout@v2
        with:
          repository: levigo/action-jira
          ref: refs/tags/v7
          path: action-jira
          token: ${{ secrets.REPO_PTA }} # `REPO_PTA` contains a PersonalAccessToken to clone a private repo

      ## get the docker image used for next step
      - name: get jcdc image
        env:
          REGISTRY_USERID: ${{ secrets.LEVIGO_NEXUS_USERNAME }}
          REGISTRY_CREDENTIALS: ${{ secrets.LEVIGO_NEXUS_PASSWORD }}
          REGISTRY_URL: 'registry.jadice.com'
        run: |
          docker login ${REGISTRY_URL} --username ${REGISTRY_USERID} --password ${REGISTRY_CREDENTIALS}
          docker pull registry.jadice.com/jira-cd-client:1.0.29

      ## create a release and publish it and also add a comment for the JIRA issue parsed from the commit message
      - name: notify JIRA
        uses: ./action-jira
        with:
          runnable: "ReleaseRunnable"
          jira-base-url: "${{ secrets.JIRA_BASE_URL }}"
          jira-user: "${{ secrets.JIRA_USER }}"
          jira-password: "${{ secrets.JIRA_PASSWORD }}"
          jira-projet-key: "DOCPV"
          release-version: "${{ steps.semanticversion.outputs.new_version }}"
          git-commitHash: "${{ github.sha }}"
          git-repositoryPath: "./.git"
          dryrun: "false"
          archived: "false"

      ## Update README.md
      - name: Edit README.md to contain version number
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git reset --hard HEAD

          sed -ri "s,<version>.*</version>,<version>${{ steps.semanticversion.outputs.new_version }}</version>," README.md
          sed -ri "s,version-[0-9a-z.]+-,version-${{ steps.semanticversion.outputs.new_version }}-," README.md
          sed -ri "s,releases/tag/documentplatform-standard14-fonts-[0-9a-z._-]+,releases/tag/${{ steps.semanticversion.outputs.new_tag }}," README.md
          cat README.md

          git add README.md
          git commit -m "Edit README.md to contain correct version"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.REPO_PTA }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          #don't use the GITHUB_TOKEN https://github:community/t/actions-not-triggered-on-release/17944/12:
          GITHUB_TOKEN: ${{ secrets.REPO_PTA }}
        with:
          tag_name: ${{ steps.semanticversion.outputs.new_tag }}
          release_name: ${{ steps.semanticversion.outputs.new_version }}

      ## Notify Slack
      - name: Notify slack
        uses: hennejg/slack-build-notifier@v1.1
        with:
          username: GitHub
          icon_emoji: octocat
          channel: ci_docp
          text: Released new version `${{ steps.semanticversion.outputs.new_version }}` of *${{ github.repository }}* to ${{ secrets.REPOSITORY_URL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
